r"""Build the hit-zone map for a creature sprite.

Only visible (opaque) pixels can be hit. Each opaque pixel is labelled with a
zone by simple region rules measured on the 1024 x 1024 sprite canvas, then the
canvas is reduced to a GRID x GRID map that the game rules use for hit tests.

Outputs:
  src/game/creatures/<slug>.ts            zone map + placement constants
  art/exports/creatures/<sprite>_hitzones.webp   translucent debug overlay

Usage (Inkscape's Python has Pillow):
  "C:\Program Files\Inkscape\bin\python.exe" art\tools\build_hitzones.py
"""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
GRID = 128
CELL = 1024 // GRID

# Zone codes shared with src/game/duel.ts
NONE, FACE, TORSO, LIMB, TAIL, HAT = 0, 1, 2, 3, 4, 5
COLORS = {FACE: (255, 60, 60), TORSO: (255, 170, 0), LIMB: (60, 140, 255), TAIL: (40, 220, 120), HAT: (160, 160, 160)}


def sage_zone(x: int, y: int) -> int:
    """Region rules for creature_desert-sage_front (measured on the 1024 canvas)."""
    # Face: ellipse from under the hat brim to the chin.
    if ((x - 512) / 168) ** 2 + ((y - 352) / 125) ** 2 <= 1:
        return FACE
    if y < 305:
        return HAT  # hat and brim; cosmetic, never hittable
    if y < 440:
        return LIMB  # ears
    if 345 <= x <= 690 and y <= 790:
        return TORSO  # bandanna, vest, belt, belly
    if y >= 790:
        return LIMB  # legs and boots
    if x >= 770 or (x >= 690 and y > 770):
        return TAIL
    return LIMB  # arms, hands, holster


CREATURES = [
    {
        "slug": "desert-sage",
        "sprite": "art/exports/creatures/creature_desert-sage_front.png",
        "zone": sage_zone,
        # Placement on the canvas: torso reference point and sole baseline.
        "torso_px": (512, 600),
        "baseline_y": 944,
    },
]


def build(c: dict) -> None:
    im = Image.open(ROOT / c["sprite"]).convert("RGBA")
    alpha = im.getchannel("A")
    a = alpha.load()
    counts = [[{} for _ in range(GRID)] for _ in range(GRID)]
    overlay = Image.new("RGBA", im.size, (0, 0, 0, 0))
    o = overlay.load()
    for y in range(1024):
        for x in range(1024):
            if a[x, y] < 128:
                continue
            z = c["zone"](x, y)
            cell = counts[y // CELL][x // CELL]
            cell[z] = cell.get(z, 0) + 1
            r, g, b = COLORS[z]
            o[x, y] = (r, g, b, 110)
    rows = []
    for gy in range(GRID):
        row = []
        for gx in range(GRID):
            cell = counts[gy][gx]
            opaque = sum(cell.values())
            # A cell is hittable when at least a quarter of it is visible.
            row.append(str(max(cell, key=cell.get)) if opaque >= CELL * CELL // 4 else "0")
        rows.append("".join(row))
    slug = c["slug"]
    ts = ROOT / "src/game/creatures" / f"{slug}.ts"
    ts.write_text(
        "// GENERATED by art/tools/build_hitzones.py. Do not edit by hand.\n"
        f"// Hit zones for {Path(c['sprite']).name}: 0 none, 1 face, 2 torso, 3 limb, 4 tail, 5 hat (miss).\n"
        "import type { CreatureZones } from './types';\n\n"
        f"export const {slug.replace('-', '_').upper()}: CreatureZones = {{\n"
        f"  slug: '{slug}',\n"
        f"  canvas: 1024,\n  grid: {GRID},\n"
        f"  torsoPx: [{c['torso_px'][0]}, {c['torso_px'][1]}],\n"
        f"  baselineY: {c['baseline_y']},\n"
        "  rows: [\n" + "".join(f"    '{r}',\n" for r in rows) + "  ],\n};\n",
        encoding="utf-8",
    )
    out = ROOT / "art/exports/creatures" / (Path(c["sprite"]).stem + "_hitzones.webp")
    overlay.save(out, "WEBP", quality=70, method=6)
    print(f"wrote {ts.relative_to(ROOT)} and {out.relative_to(ROOT)}")


if __name__ == "__main__":
    for creature in CREATURES:
        build(creature)
